services:
  - type: web
    name: jaaz-backend
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DATABASE_URL
        value: sqlite:///./user_data/localmanus.db
    disk:
      name: jaaz-data
      mountPath: /app/user_data
      sizeGB: 1